[features]
seeds = false
[programs.localnet]
dojbridge = "8fK3EArbLPuao6tZVAn6te9yJkxAHay2JcBcauk61cBN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/abhishek/.config/solana/id.json"
dojbridge = "8fK3EArbLPuao6tZVAn6te9yJkxAHay2JcBcauk61cBN"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
